name: amplitude_flutter_new
description: Amplitude Flutter plugin
version: 1.0.0
homepage: https://www.amplitude.com
repository: https://github.com/ps6067966/Amplitude-Flutter


environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.amplitude.amplitude_flutter_new
        pluginClass: AmplitudeFlutterPlugin
      ios:
        pluginClass: AmplitudeFlutterPlugin
      web:
        pluginClass: AmplitudeFlutterPlugin
        fileName: amplitude_web.dart
